### ISSUE TITLE
Indicate recording when recording

### ISSUE THREAD

**Issue by mcfnord** [dtinth/jamulus-lounge#6]
Hi.

I'd like the lobby icon to indicate in Jamulus that it's recording when it is recording.

Maybe [the worker function](https://github.com/dtinth/jamulus-lounge/blob/1257a9a4376590ed113905a24faa9721f6a668a2/server/index.mjs#L34) can choose the instrument based on recording status.

Instrument 24 is a streamer icon, and instrument 23 is a recorder icon.

I think I'd like to change the instrument value within the worker loop in **server/index.mjs** [based on **AudioRecorder.stopped** value](https://github.com/dtinth/jamulus-lounge/blob/1257a9a4376590ed113905a24faa9721f6a668a2/public/main.mjs#L186-L202) in **public/main.mjs**.

I am concerned that these two source files are in different directories, and might even run as different processes. Maybe linking one to the other isn't simple.

I have a backup plan, where I add a --norecord flag to the server, which uses a streamer icon with no recording button. By default, the recording icon is used throughout the session.

I hope you can give me your feedback.

**Comment by dtinth** [comment]
you are right that it isn’t simple.

right now a single stream is used for both listening and recording. as far as the server is concerned, there is no difference between a client listening or recording. in fact, if a client starts recording while listening, it reuses the same data stream.

the argument goes that even with recording disabled, people can just use other software to record the listen stream. the record button just makes it more convenient for people who wants to record sessions. (we have people practicing in my server who records their sessions this way.)

**Comment by mcfnord** [comment]
I want to offer recording again, because many people used it to record their sessions. Others got upset about the ease of recording. Better disclosure would address some of their concerns.

I think I understand how gojam doesn't know if anyone within lounge is recording or just listening.

The REC icon for a lobby that can record would indicate more clearly that recording is possible. Ultimately, maybe a localized explanation in chat is needed.
